FROM oven/bun:alpine

WORKDIR /app

ENV NODE_ENV=development

RUN chown bun:bun /app

USER bun

COPY --chown=bun:bun package.json bun.lock ./
RUN bun install

COPY --chown=bun:bun . .

EXPOSE 3000

CMD ["bun", "run", "dev"]
