FROM golang:1.26.1-alpine

WORKDIR /app

RUN apk add --no-cache curl tar git gcc musl-dev ffmpeg

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz && \
    mv migrate /usr/local/bin/migrate

COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

CMD ["sh", "-c", "migrate -path=./db/migrations/ -database \"postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable\" up && go test -p 1 -v ./..."]
