FROM golang:alpine

WORKDIR /app

ENV ENV=development
ENV GEOIP_DB_PATH=./GeoLite2-City.mmdb

RUN apk add --no-cache git make && \
    adduser -D app && \
    chown app:app /app

USER app

RUN go install github.com/air-verse/air@latest

# Download dependencies
COPY --chown=app:app go.mod go.sum ./
RUN go mod download

# Copy the rest of the code
COPY --chown=app:app . .

# Expose the API port
EXPOSE 8080

# Run Air for development hot reloading
CMD ["air", "-c", ".air.toml"]
