FROM alpine:latest

RUN apk add --no-cache curl tar && \
    curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz && \
    mv migrate /usr/local/bin/migrate && \
    adduser -D app

# Copy migrations
COPY --chown=app:app ./db/migrations /migrations

USER app

# Entrypoint
ENTRYPOINT ["migrate"]
CMD ["-path=/migrations/", "up"]
