// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ad_categories.sql

package repository

import (
	"context"
)

const getCategoryMultiplier = `-- name: GetCategoryMultiplier :one
SELECT multiplier FROM ad_categories WHERE category = $1 LIMIT 1
`

func (q *Queries) GetCategoryMultiplier(ctx context.Context, category string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCategoryMultiplier, category)
	var multiplier string
	err := row.Scan(&multiplier)
	return multiplier, err
}

const listAdCategories = `-- name: ListAdCategories :many
SELECT category, label, multiplier FROM ad_categories ORDER BY category
`

func (q *Queries) ListAdCategories(ctx context.Context) ([]AdCategory, error) {
	rows, err := q.db.QueryContext(ctx, listAdCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdCategory
	for rows.Next() {
		var i AdCategory
		if err := rows.Scan(&i.Category, &i.Label, &i.Multiplier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
