// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ad_events.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAdEvent = `-- name: CreateAdEvent :one
INSERT INTO ad_events (
    ad_id, link_id, event_type, is_valid, quality_score, rejection_reason, ip_address, user_agent, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, ad_id, link_id, event_type, is_valid, quality_score, rejection_reason, ip_address, user_agent, metadata, created_at
`

type CreateAdEventParams struct {
	AdID            uuid.UUID             `json:"ad_id"`
	LinkID          uuid.UUID             `json:"link_id"`
	EventType       string                `json:"event_type"`
	IsValid         bool                  `json:"is_valid"`
	QualityScore    string                `json:"quality_score"`
	RejectionReason sql.NullString        `json:"rejection_reason"`
	IpAddress       pqtype.Inet           `json:"ip_address"`
	UserAgent       sql.NullString        `json:"user_agent"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateAdEvent(ctx context.Context, arg CreateAdEventParams) (AdEvent, error) {
	row := q.db.QueryRowContext(ctx, createAdEvent,
		arg.AdID,
		arg.LinkID,
		arg.EventType,
		arg.IsValid,
		arg.QualityScore,
		arg.RejectionReason,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AdEvent
	err := row.Scan(
		&i.ID,
		&i.AdID,
		&i.LinkID,
		&i.EventType,
		&i.IsValid,
		&i.QualityScore,
		&i.RejectionReason,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAdEventStats = `-- name: GetAdEventStats :one
SELECT 
    COUNT(*) FILTER (WHERE event_type = 'IMPRESSION') as impressions,
    COUNT(*) FILTER (WHERE event_type = 'CLICK') as clicks,
    COUNT(*) FILTER (WHERE event_type = 'COMPLETION') as completions
FROM ad_events 
WHERE ad_id = $1
`

type GetAdEventStatsRow struct {
	Impressions int64 `json:"impressions"`
	Clicks      int64 `json:"clicks"`
	Completions int64 `json:"completions"`
}

func (q *Queries) GetAdEventStats(ctx context.Context, adID uuid.UUID) (GetAdEventStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAdEventStats, adID)
	var i GetAdEventStatsRow
	err := row.Scan(&i.Impressions, &i.Clicks, &i.Completions)
	return i, err
}
