// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ads.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countAdsByAdvertiser = `-- name: CountAdsByAdvertiser :one
SELECT COUNT(*) FROM ads WHERE advertiser_id = $1
`

func (q *Queries) CountAdsByAdvertiser(ctx context.Context, advertiserID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdsByAdvertiser, advertiserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdsByAdvertiserFiltered = `-- name: CountAdsByAdvertiserFiltered :one
SELECT COUNT(*) FROM ads
WHERE advertiser_id = $1
  AND ($2::text IS NULL OR $2 = '' OR title ILIKE '%' || $2 || '%')
`

type CountAdsByAdvertiserFilteredParams struct {
	AdvertiserID uuid.UUID      `json:"advertiser_id"`
	Q            sql.NullString `json:"q"`
}

func (q *Queries) CountAdsByAdvertiserFiltered(ctx context.Context, arg CountAdsByAdvertiserFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdsByAdvertiserFiltered, arg.AdvertiserID, arg.Q)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAd = `-- name: CreateAd :one
INSERT INTO ads (
    advertiser_id, title, description, image_url, target_url, category, total_budget, remaining_budget, cpm, ad_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, advertiser_id, title, description, image_url, target_url, category, ad_type, total_budget, remaining_budget, cpm, status, created_at, updated_at
`

type CreateAdParams struct {
	AdvertiserID    uuid.UUID      `json:"advertiser_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	ImageUrl        string         `json:"image_url"`
	TargetUrl       string         `json:"target_url"`
	Category        string         `json:"category"`
	TotalBudget     string         `json:"total_budget"`
	RemainingBudget string         `json:"remaining_budget"`
	Cpm             string         `json:"cpm"`
	AdType          string         `json:"ad_type"`
}

func (q *Queries) CreateAd(ctx context.Context, arg CreateAdParams) (Ad, error) {
	row := q.db.QueryRowContext(ctx, createAd,
		arg.AdvertiserID,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.TargetUrl,
		arg.Category,
		arg.TotalBudget,
		arg.RemainingBudget,
		arg.Cpm,
		arg.AdType,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.TargetUrl,
		&i.Category,
		&i.AdType,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.Cpm,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deductAdBudget = `-- name: DeductAdBudget :exec
UPDATE ads 
SET remaining_budget = remaining_budget - $2, updated_at = NOW() 
WHERE id = $1 AND remaining_budget >= $2
`

type DeductAdBudgetParams struct {
	ID              uuid.UUID `json:"id"`
	RemainingBudget string    `json:"remaining_budget"`
}

func (q *Queries) DeductAdBudget(ctx context.Context, arg DeductAdBudgetParams) error {
	_, err := q.db.ExecContext(ctx, deductAdBudget, arg.ID, arg.RemainingBudget)
	return err
}

const getActiveAds = `-- name: GetActiveAds :many
SELECT id, advertiser_id, title, description, image_url, target_url, category, ad_type, total_budget, remaining_budget, cpm, status, created_at, updated_at FROM ads 
WHERE status = 'active' 
AND remaining_budget >= (cpm / 1000)
ORDER BY cpm DESC
`

func (q *Queries) GetActiveAds(ctx context.Context) ([]Ad, error) {
	rows, err := q.db.QueryContext(ctx, getActiveAds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ad
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.TargetUrl,
			&i.Category,
			&i.AdType,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.Cpm,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveAdsByCategory = `-- name: GetActiveAdsByCategory :many
SELECT id, advertiser_id, title, description, image_url, target_url, category, ad_type, total_budget, remaining_budget, cpm, status, created_at, updated_at FROM ads 
WHERE status = 'active' 
AND remaining_budget >= (cpm / 1000)
AND category = ANY($1::text[])
ORDER BY cpm DESC
`

func (q *Queries) GetActiveAdsByCategory(ctx context.Context, dollar_1 []string) ([]Ad, error) {
	rows, err := q.db.QueryContext(ctx, getActiveAdsByCategory, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ad
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.TargetUrl,
			&i.Category,
			&i.AdType,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.Cpm,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdByID = `-- name: GetAdByID :one
SELECT id, advertiser_id, title, description, image_url, target_url, category, ad_type, total_budget, remaining_budget, cpm, status, created_at, updated_at FROM ads WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdByID(ctx context.Context, id uuid.UUID) (Ad, error) {
	row := q.db.QueryRowContext(ctx, getAdByID, id)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.TargetUrl,
		&i.Category,
		&i.AdType,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.Cpm,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCPMByAdType = `-- name: GetCPMByAdType :one
SELECT cpm FROM ad_cpm_rates WHERE ad_type = $1 LIMIT 1
`

func (q *Queries) GetCPMByAdType(ctx context.Context, adType string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCPMByAdType, adType)
	var cpm string
	err := row.Scan(&cpm)
	return cpm, err
}

const getReferencedMediaURLs = `-- name: GetReferencedMediaURLs :many
SELECT image_url
FROM ads
WHERE image_url IS NOT NULL
  AND image_url <> ''
  AND status <> 'deleted'
`

func (q *Queries) GetReferencedMediaURLs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getReferencedMediaURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_url string
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdTypes = `-- name: ListAdTypes :many
SELECT t.ad_type, c.cpm, t.label, t.aspect_ratio, t.recommended_resolution
FROM ad_types t
LEFT JOIN ad_cpm_rates c ON t.ad_type = c.ad_type
ORDER BY c.cpm ASC
`

type ListAdTypesRow struct {
	AdType                string         `json:"ad_type"`
	Cpm                   sql.NullString `json:"cpm"`
	Label                 string         `json:"label"`
	AspectRatio           string         `json:"aspect_ratio"`
	RecommendedResolution string         `json:"recommended_resolution"`
}

func (q *Queries) ListAdTypes(ctx context.Context) ([]ListAdTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdTypesRow
	for rows.Next() {
		var i ListAdTypesRow
		if err := rows.Scan(
			&i.AdType,
			&i.Cpm,
			&i.Label,
			&i.AspectRatio,
			&i.RecommendedResolution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdsByAdvertiser = `-- name: ListAdsByAdvertiser :many
SELECT id, advertiser_id, title, description, image_url, target_url, category, ad_type, total_budget, remaining_budget, cpm, status, created_at, updated_at FROM ads WHERE advertiser_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAdsByAdvertiser(ctx context.Context, advertiserID uuid.UUID) ([]Ad, error) {
	rows, err := q.db.QueryContext(ctx, listAdsByAdvertiser, advertiserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ad
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.TargetUrl,
			&i.Category,
			&i.AdType,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.Cpm,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdsByAdvertiserFiltered = `-- name: ListAdsByAdvertiserFiltered :many
SELECT id, advertiser_id, title, description, image_url, target_url, category, ad_type, total_budget, remaining_budget, cpm, status, created_at, updated_at FROM ads
WHERE advertiser_id = $1
  AND ($2::text IS NULL OR $2 = '' OR title ILIKE '%' || $2 || '%')
ORDER BY
  CASE WHEN $3::text = 'title' AND $4::text = 'asc' THEN title END ASC NULLS LAST,
  CASE WHEN $3::text = 'title' AND $4::text = 'desc' THEN title END DESC NULLS LAST,
  CASE WHEN $3::text = 'status' AND $4::text = 'asc' THEN status END ASC NULLS LAST,
  CASE WHEN $3::text = 'status' AND $4::text = 'desc' THEN status END DESC NULLS LAST,
  CASE WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN created_at::text END ASC NULLS LAST,
  CASE WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN created_at::text END DESC NULLS LAST,
  CASE WHEN $3::text = 'budget' AND $4::text = 'asc' THEN remaining_budget END ASC NULLS LAST,
  CASE WHEN $3::text = 'budget' AND $4::text = 'desc' THEN remaining_budget END DESC NULLS LAST,
  CASE WHEN $3::text = 'cpm' AND $4::text = 'asc' THEN cpm END ASC NULLS LAST,
  CASE WHEN $3::text = 'cpm' AND $4::text = 'desc' THEN cpm END DESC NULLS LAST,
  created_at DESC
LIMIT $6 OFFSET $5
`

type ListAdsByAdvertiserFilteredParams struct {
	AdvertiserID uuid.UUID      `json:"advertiser_id"`
	Q            sql.NullString `json:"q"`
	SortBy       string         `json:"sort_by"`
	SortDir      string         `json:"sort_dir"`
	Offset       int32          `json:"offset"`
	Limit        int32          `json:"limit"`
}

func (q *Queries) ListAdsByAdvertiserFiltered(ctx context.Context, arg ListAdsByAdvertiserFilteredParams) ([]Ad, error) {
	rows, err := q.db.QueryContext(ctx, listAdsByAdvertiserFiltered,
		arg.AdvertiserID,
		arg.Q,
		arg.SortBy,
		arg.SortDir,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ad
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.TargetUrl,
			&i.Category,
			&i.AdType,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.Cpm,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAd = `-- name: UpdateAd :one
UPDATE ads SET
    title = $2,
    description = $3,
    image_url = $4,
    target_url = $5,
    category = $6,
    total_budget = $7,
    remaining_budget = $8,
    cpm = $9,
    status = $10,
    ad_type = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, advertiser_id, title, description, image_url, target_url, category, ad_type, total_budget, remaining_budget, cpm, status, created_at, updated_at
`

type UpdateAdParams struct {
	ID              uuid.UUID      `json:"id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	ImageUrl        string         `json:"image_url"`
	TargetUrl       string         `json:"target_url"`
	Category        string         `json:"category"`
	TotalBudget     string         `json:"total_budget"`
	RemainingBudget string         `json:"remaining_budget"`
	Cpm             string         `json:"cpm"`
	Status          string         `json:"status"`
	AdType          string         `json:"ad_type"`
}

func (q *Queries) UpdateAd(ctx context.Context, arg UpdateAdParams) (Ad, error) {
	row := q.db.QueryRowContext(ctx, updateAd,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.TargetUrl,
		arg.Category,
		arg.TotalBudget,
		arg.RemainingBudget,
		arg.Cpm,
		arg.Status,
		arg.AdType,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.TargetUrl,
		&i.Category,
		&i.AdType,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.Cpm,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdStatus = `-- name: UpdateAdStatus :exec
UPDATE ads SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAdStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAdStatus(ctx context.Context, arg UpdateAdStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAdStatus, arg.ID, arg.Status)
	return err
}
