// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clicks.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAggregateStatsByUser = `-- name: GetAggregateStatsByUser :many
SELECT
    c.country,
    c.device,
    c.browser,
    DATE(c.clicked_at) as click_date,
    COUNT(c.id) as click_count
FROM clicks c
JOIN urls u ON c.url_id = u.id
WHERE u.user_id = $1
GROUP BY c.country, c.device, c.browser, DATE(c.clicked_at)
ORDER BY click_date DESC
`

type GetAggregateStatsByUserRow struct {
	Country    sql.NullString `json:"country"`
	Device     sql.NullString `json:"device"`
	Browser    sql.NullString `json:"browser"`
	ClickDate  time.Time      `json:"click_date"`
	ClickCount int64          `json:"click_count"`
}

func (q *Queries) GetAggregateStatsByUser(ctx context.Context, userID uuid.UUID) ([]GetAggregateStatsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAggregateStatsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAggregateStatsByUserRow
	for rows.Next() {
		var i GetAggregateStatsByUserRow
		if err := rows.Scan(
			&i.Country,
			&i.Device,
			&i.Browser,
			&i.ClickDate,
			&i.ClickCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsBySlug = `-- name: GetStatsBySlug :many
SELECT
    c.country,
    c.device,
    c.browser,
    DATE(c.clicked_at) as click_date,
    COUNT(c.id) as click_count
FROM clicks c
JOIN urls u ON c.url_id = u.id
WHERE u.slug = $1
GROUP BY c.country, c.device, c.browser, DATE(c.clicked_at)
ORDER BY click_date DESC
`

type GetStatsBySlugRow struct {
	Country    sql.NullString `json:"country"`
	Device     sql.NullString `json:"device"`
	Browser    sql.NullString `json:"browser"`
	ClickDate  time.Time      `json:"click_date"`
	ClickCount int64          `json:"click_count"`
}

func (q *Queries) GetStatsBySlug(ctx context.Context, slug string) ([]GetStatsBySlugRow, error) {
	rows, err := q.db.QueryContext(ctx, getStatsBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsBySlugRow
	for rows.Next() {
		var i GetStatsBySlugRow
		if err := rows.Scan(
			&i.Country,
			&i.Device,
			&i.Browser,
			&i.ClickDate,
			&i.ClickCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalClicksBySlug = `-- name: GetTotalClicksBySlug :one
SELECT COUNT(*) FROM clicks c
JOIN urls u ON c.url_id = u.id
WHERE u.slug = $1
`

func (q *Queries) GetTotalClicksBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalClicksBySlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalClicksByUser = `-- name: GetTotalClicksByUser :one
SELECT COUNT(*) FROM clicks c
JOIN urls u ON c.url_id = u.id
WHERE u.user_id = $1
`

func (q *Queries) GetTotalClicksByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalClicksByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUniqueClicksBySlug = `-- name: GetUniqueClicksBySlug :one
SELECT COUNT(DISTINCT c.ip_hash) FROM clicks c
JOIN urls u ON c.url_id = u.id
WHERE u.slug = $1 AND c.ip_hash IS NOT NULL
`

func (q *Queries) GetUniqueClicksBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUniqueClicksBySlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUniqueClicksByUser = `-- name: GetUniqueClicksByUser :one
SELECT COUNT(DISTINCT c.ip_hash) FROM clicks c
JOIN urls u ON c.url_id = u.id
WHERE u.user_id = $1 AND c.ip_hash IS NOT NULL
`

func (q *Queries) GetUniqueClicksByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUniqueClicksByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const saveClick = `-- name: SaveClick :one
INSERT INTO clicks (
  url_id, ip_hash, country, city, device, browser, referrer
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, url_id, ip_hash, country, city, device, browser, referrer, clicked_at
`

type SaveClickParams struct {
	UrlID    uuid.UUID      `json:"url_id"`
	IpHash   sql.NullString `json:"ip_hash"`
	Country  sql.NullString `json:"country"`
	City     sql.NullString `json:"city"`
	Device   sql.NullString `json:"device"`
	Browser  sql.NullString `json:"browser"`
	Referrer sql.NullString `json:"referrer"`
}

func (q *Queries) SaveClick(ctx context.Context, arg SaveClickParams) (Click, error) {
	row := q.db.QueryRowContext(ctx, saveClick,
		arg.UrlID,
		arg.IpHash,
		arg.Country,
		arg.City,
		arg.Device,
		arg.Browser,
		arg.Referrer,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.IpHash,
		&i.Country,
		&i.City,
		&i.Device,
		&i.Browser,
		&i.Referrer,
		&i.ClickedAt,
	)
	return i, err
}
