// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Click struct {
	ID        uuid.UUID      `json:"id"`
	UrlID     uuid.UUID      `json:"url_id"`
	IpHash    sql.NullString `json:"ip_hash"`
	Country   sql.NullString `json:"country"`
	City      sql.NullString `json:"city"`
	Device    sql.NullString `json:"device"`
	Browser   sql.NullString `json:"browser"`
	Referrer  sql.NullString `json:"referrer"`
	ClickedAt time.Time      `json:"clicked_at"`
}

type Url struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Slug      string       `json:"slug"`
	Original  string       `json:"original"`
	Custom    bool         `json:"custom"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}