// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Ad struct {
	ID              uuid.UUID      `json:"id"`
	AdvertiserID    uuid.UUID      `json:"advertiser_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	ImageUrl        string         `json:"image_url"`
	TargetUrl       string         `json:"target_url"`
	Category        string         `json:"category"`
	AdType          string         `json:"ad_type"`
	TotalBudget     string         `json:"total_budget"`
	RemainingBudget string         `json:"remaining_budget"`
	Cpm             string         `json:"cpm"`
	Status          string         `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type AdCategory struct {
	Category   string `json:"category"`
	Label      string `json:"label"`
	Multiplier string `json:"multiplier"`
}

type AdCpmRate struct {
	AdType string `json:"ad_type"`
	Cpm    string `json:"cpm"`
}

type AdEvent struct {
	ID              uuid.UUID             `json:"id"`
	AdID            uuid.UUID             `json:"ad_id"`
	LinkID          uuid.UUID             `json:"link_id"`
	EventType       string                `json:"event_type"`
	IsValid         bool                  `json:"is_valid"`
	QualityScore    string                `json:"quality_score"`
	RejectionReason sql.NullString        `json:"rejection_reason"`
	IpAddress       pqtype.Inet           `json:"ip_address"`
	UserAgent       sql.NullString        `json:"user_agent"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	CreatedAt       time.Time             `json:"created_at"`
}

type AdType struct {
	AdType                string `json:"ad_type"`
	Label                 string `json:"label"`
	AspectRatio           string `json:"aspect_ratio"`
	RecommendedResolution string `json:"recommended_resolution"`
}

type Click struct {
	ID        uuid.UUID      `json:"id"`
	UrlID     uuid.UUID      `json:"url_id"`
	IpHash    sql.NullString `json:"ip_hash"`
	Country   sql.NullString `json:"country"`
	City      sql.NullString `json:"city"`
	Device    sql.NullString `json:"device"`
	Browser   sql.NullString `json:"browser"`
	Referrer  sql.NullString `json:"referrer"`
	ClickedAt time.Time      `json:"clicked_at"`
}

type FaucetClaim struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Amount    string         `json:"amount"`
	TxHash    sql.NullString `json:"tx_hash"`
	ClaimedAt time.Time      `json:"claimed_at"`
}

type OauthAccount struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Provider   string    `json:"provider"`
	ProviderID string    `json:"provider_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Transaction struct {
	ID        uuid.UUID             `json:"id"`
	UserID    uuid.UUID             `json:"user_id"`
	Amount    string                `json:"amount"`
	Type      string                `json:"type"`
	Status    string                `json:"status"`
	TxHash    sql.NullString        `json:"tx_hash"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt time.Time             `json:"created_at"`
}

type Url struct {
	ID                uuid.UUID    `json:"id"`
	UserID            uuid.UUID    `json:"user_id"`
	Slug              string       `json:"slug"`
	Original          string       `json:"original"`
	Custom            bool         `json:"custom"`
	ExpiresAt         sql.NullTime `json:"expires_at"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	IsMonetized       bool         `json:"is_monetized"`
	AllowedCategories []string     `json:"allowed_categories"`
}

type User struct {
	ID                      uuid.UUID      `json:"id"`
	Name                    string         `json:"name"`
	Email                   string         `json:"email"`
	Password                sql.NullString `json:"password"`
	CreatedAt               time.Time      `json:"created_at"`
	Role                    string         `json:"role"`
	EmailVerified           bool           `json:"email_verified"`
	EmailVerificationToken  sql.NullString `json:"email_verification_token"`
	EmailVerificationSentAt sql.NullTime   `json:"email_verification_sent_at"`
	PasswordResetToken      sql.NullString `json:"password_reset_token"`
	PasswordResetSentAt     sql.NullTime   `json:"password_reset_sent_at"`
}

type Wallet struct {
	UserID    uuid.UUID `json:"user_id"`
	Balance   string    `json:"balance"`
	UpdatedAt time.Time `json:"updated_at"`
}
