// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :exec
INSERT INTO oauth_accounts (user_id, provider, provider_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type CreateOAuthAccountParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Provider   string    `json:"provider"`
	ProviderID string    `json:"provider_id"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthAccount, arg.UserID, arg.Provider, arg.ProviderID)
	return err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :exec
DELETE FROM oauth_accounts WHERE id = $1
`

func (q *Queries) DeleteOAuthAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthAccount, id)
	return err
}

const getOAuthAccountByProvider = `-- name: GetOAuthAccountByProvider :one
SELECT id, user_id, provider, provider_id, created_at FROM oauth_accounts
WHERE provider = $1 AND provider_id = $2
LIMIT 1
`

type GetOAuthAccountByProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetOAuthAccountByProvider(ctx context.Context, arg GetOAuthAccountByProviderParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByProvider, arg.Provider, arg.ProviderID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthAccountsByUserID = `-- name: ListOAuthAccountsByUserID :many
SELECT id, user_id, provider, provider_id, created_at FROM oauth_accounts WHERE user_id = $1
`

func (q *Queries) ListOAuthAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error) {
	rows, err := q.db.QueryContext(ctx, listOAuthAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthAccount
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
