// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountURLsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredURLs(ctx context.Context) error
	DeleteURL(ctx context.Context, arg DeleteURLParams) error
	GetAggregateStatsByUser(ctx context.Context, userID uuid.UUID) ([]GetAggregateStatsByUserRow, error)
	GetStatsBySlug(ctx context.Context, slug string) ([]GetStatsBySlugRow, error)
	GetTotalClicksBySlug(ctx context.Context, slug string) (int64, error)
	GetTotalClicksByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	GetURLBySlug(ctx context.Context, slug string) (Url, error)
	GetUniqueClicksBySlug(ctx context.Context, slug string) (int64, error)
	GetUniqueClicksByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListURLsByUser(ctx context.Context, userID uuid.UUID) ([]Url, error)
	ListURLsByUserPaginated(ctx context.Context, arg ListURLsByUserPaginatedParams) ([]Url, error)
	SaveClick(ctx context.Context, arg SaveClickParams) (Click, error)
	UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error)
}

var _ Querier = (*Queries)(nil)
