// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countURLsByUser = `-- name: CountURLsByUser :one
SELECT COUNT(*) FROM urls WHERE user_id = $1
`

func (q *Queries) CountURLsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countURLsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
  user_id, slug, original, custom, expires_at, is_monetized, allowed_categories
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, slug, original, custom, expires_at, created_at, updated_at, is_monetized, allowed_categories
`

type CreateURLParams struct {
	UserID            uuid.UUID    `json:"user_id"`
	Slug              string       `json:"slug"`
	Original          string       `json:"original"`
	Custom            bool         `json:"custom"`
	ExpiresAt         sql.NullTime `json:"expires_at"`
	IsMonetized       bool         `json:"is_monetized"`
	AllowedCategories []string     `json:"allowed_categories"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.UserID,
		arg.Slug,
		arg.Original,
		arg.Custom,
		arg.ExpiresAt,
		arg.IsMonetized,
		pq.Array(arg.AllowedCategories),
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Original,
		&i.Custom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsMonetized,
		pq.Array(&i.AllowedCategories),
	)
	return i, err
}

const deleteExpiredURLs = `-- name: DeleteExpiredURLs :exec
DELETE FROM urls
WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredURLs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredURLs)
	return err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls
WHERE id = $1 AND user_id = $2
`

type DeleteURLParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteURL(ctx context.Context, arg DeleteURLParams) error {
	_, err := q.db.ExecContext(ctx, deleteURL, arg.ID, arg.UserID)
	return err
}

const getURLBySlug = `-- name: GetURLBySlug :one
SELECT id, user_id, slug, original, custom, expires_at, created_at, updated_at, is_monetized, allowed_categories FROM urls
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetURLBySlug(ctx context.Context, slug string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLBySlug, slug)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Original,
		&i.Custom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsMonetized,
		pq.Array(&i.AllowedCategories),
	)
	return i, err
}

const listURLsByUser = `-- name: ListURLsByUser :many
SELECT id, user_id, slug, original, custom, expires_at, created_at, updated_at, is_monetized, allowed_categories FROM urls
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListURLsByUser(ctx context.Context, userID uuid.UUID) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Original,
			&i.Custom,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsMonetized,
			pq.Array(&i.AllowedCategories),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listURLsByUserPaginated = `-- name: ListURLsByUserPaginated :many
SELECT id, user_id, slug, original, custom, expires_at, created_at, updated_at, is_monetized, allowed_categories FROM urls
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListURLsByUserPaginatedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListURLsByUserPaginated(ctx context.Context, arg ListURLsByUserPaginatedParams) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, listURLsByUserPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Original,
			&i.Custom,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsMonetized,
			pq.Array(&i.AllowedCategories),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls
SET slug = $2, expires_at = $3, is_monetized = $5, allowed_categories = $6, updated_at = NOW()
WHERE id = $1 AND user_id = $4
RETURNING id, user_id, slug, original, custom, expires_at, created_at, updated_at, is_monetized, allowed_categories
`

type UpdateURLParams struct {
	ID                uuid.UUID    `json:"id"`
	Slug              string       `json:"slug"`
	ExpiresAt         sql.NullTime `json:"expires_at"`
	UserID            uuid.UUID    `json:"user_id"`
	IsMonetized       bool         `json:"is_monetized"`
	AllowedCategories []string     `json:"allowed_categories"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateURL,
		arg.ID,
		arg.Slug,
		arg.ExpiresAt,
		arg.UserID,
		arg.IsMonetized,
		pq.Array(arg.AllowedCategories),
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Original,
		&i.Custom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsMonetized,
		pq.Array(&i.AllowedCategories),
	)
	return i, err
}
