// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO wallets (user_id, balance) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreateWalletParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Balance string    `json:"balance"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) error {
	_, err := q.db.ExecContext(ctx, createWallet, arg.UserID, arg.Balance)
	return err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT user_id, balance, updated_at FROM wallets WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWalletByUserID, userID)
	var i Wallet
	err := row.Scan(&i.UserID, &i.Balance, &i.UpdatedAt)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :one
UPDATE wallets 
SET balance = balance + $2, updated_at = NOW() 
WHERE user_id = $1 
RETURNING user_id, balance, updated_at
`

type UpdateWalletBalanceParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Balance string    `json:"balance"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, updateWalletBalance, arg.UserID, arg.Balance)
	var i Wallet
	err := row.Scan(&i.UserID, &i.Balance, &i.UpdatedAt)
	return i, err
}
